### ISSUE TITLE
Releasing mBART

### ISSUE THREAD

**Issue by stephanpeitz** [pytorch/fairseq#1676] opened 2020-02-04 20:50 UTC
Hi Fairseq team,

are you plaining to release mBART25 described in [(Liu et al., arXiv 2020)](https://arxiv.org/pdf/2001.08210v2.pdf)?

Cheers,
Stephan

**Comment by pipibjc** [comment] 2020-02-04 22:15
Duplicate of #1670

**Closed** 2020-02-04 22:15 UTC
Labels: needs triage, question

**Comment by hamediramin** [comment] 2020-02-24 16:50
Yes would love to see what happens here

**Comment by yinhanliu** [comment] 2020-02-27 18:59
https://github.com/pytorch/fairseq/commit/5e79322b3a4a9e9a11525377d3dda7ac520b921c

**Comment by yinhanliu** [comment] 2020-02-27 19:00
@hamediramin  @stephanpeitz @pipibjc  It is opensourced here https://github.com/pytorch/fairseq/tree/master/examples/mbart

**Comment by stephanpeitz** [comment] 2020-02-27 20:25
Thanks for letting us know!
