### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by elfsmelf** [pytorch/fairseq#271] opened 2018-09-06 12:58 UTC
@huihuifan 

OSError: Model file not found: C

Command:

`python generate.py data-bin/writingPrompts --path C:/Users/Richard/Documents/story_creation/fairseq-master/fairseq/models/pretrained_checkpoint.pt --batch-size 32 --beam 1 --sampling --sampling-topk 10 --sampling-temperature 0.8 --nbest 1 --model-overrides "{'pretrained_checkpoint':'C:/Users/Richard/Documents/story_creation/fairseq-master/fairseq/models/fusion_checkpoint.pt'}"`

I am trying to use the pre-trained models, which I have saved to this directory: 
C:/Users/Richard/Documents/story_creation/fairseq-master/fairseq/models/fusion_checkpoint.pt

Full command/error:

```
PS C:\Users\Richard\Documents\story_creation\fairseq-master> python generate.py data-bin/writingPrompts --path C:/Users/Richard/Documents/story_creation/fairseq-master/fairseq/mod
els/pretrained_checkpoint.pt --batch-size 32 --beam 1 --sampling --sampling-topk 10 --sampling-temperature 0.8 --nbest 1 --model-overrides "{'pretrained_checkpoint':'C:/Users/Rich
ard/Documents/story_creation/fairseq-master/fairseq/models/'}"
Namespace(beam=1, cpu=False, data='data-bin/writingPrompts', fp16=False, gen_subset='test', left_pad_source='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000, max_len_a=0, max_len_b=200, max_sentences=32, max_source_positions=1024, max_target_positions=1024, max_tokens=None, min_len=1, model_overrides="{'pretrained_checkpoint':'C:/Users/Richard/Documents/story_creation/fairseq-master/fairseq/models/'}", nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, num_shards=1, path='C:/Users/Richard/Documents/story_creation/fairseq-master/fairseq/models/pretrained_checkpoint.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, sampling=True, sampling_temperature=0.8, sampling_topk=10, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation', unkpen=0, unnormalized=False)
| [wp_source] dictionary: 19025 types
| [wp_target] dictionary: 112832 types
| data-bin/writingPrompts test 15138 examples
| data-bin/writingPrompts test 15138 examples
| loading model(s) from C:/Users/Richard/Documents/story_creation/fairseq-master/fairseq/models/pretrained_checkpoint.pt
Traceback (most recent call last):
  File "generate.py", line 164, in <module>
    main(args)
  File "generate.py", line 41, in main
    models, _ = utils.load_ensemble_for_inference(args.path.split(':'), task, model_arg_overrides=eval(args.model_overrides))
  File "C:\Users\Richard\Documents\story_creation\fairseq-master\fairseq\utils.py", line 145, in load_ensemble_for_inference
    raise IOError('Model file not found: {}'.format(filename))
OSError: Model file not found: C

```
I have had issues training thats why I thought I should just generate from pretrained models, do I maybe need to get training to work to be able to use the pretrained models?

Thanks!

**Comment by myleott** [comment] 2018-09-06 15:31
The problem is here: https://github.com/pytorch/fairseq/blob/master/generate.py#L44. Please change the `':'` to `','` or another separator. Basically we assume the `--path` argument is a colon-separated list of models to ensemble, but this doesn't work with Windows paths that can include colons.

**Comment by huihuifan** [comment] 2018-09-06 18:11
Yup, what Myle said above. The other thing is that I think your wp_target dictionary is a little too large.

**Comment by elfsmelf** [comment] 2018-09-07 00:47
Ahh. So I am preprocessing for too long? Is there a way to shorten it? I just let it run?

**Comment by huihuifan** [comment] 2018-09-07 01:06
Can you redownload the dataset and use this exact preprocessing command: https://github.com/pytorch/fairseq/tree/master/examples/stories

The dictionary size shouldn't be related to how long you let it run for, it constructs the dictionary and then preprocesses the data. I think you might not have set the target side threshold correctly or maybe the data is not this exact dataset.

**Comment by vanhuyz** [comment] 2018-09-07 11:40
I've just downloaded the dataset and pretrained models, used the exact preprocessing command you provided, to no avail.

Has the wp_target dictionary changed since then?

```
Namespace(beam=1, cpu=False, data='data-bin/writingPrompts', diverse_beam_groups=1, diverse_beam_strength=0.5, fp16=False, gen_subset='test', left_pad_source='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000, max_len_a=0, max_len_b=200, max_sentences=32, max_source_positions=1024, max_target_positions=1024, max_tokens=None, min_len=1, model_overrides="{'pretrained_checkpoint':'models/writingPrompts/pretrained_checkpoint.pt'}", nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, num_shards=1, path='models/writingPrompts/fusion_checkpoint.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, sampling=True, sampling_temperature=0.8, sampling_topk=10, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation', unkpen=0, unnormalized=False, upsample_primary=1)
| [wp_source] dictionary: 19025 types
| [wp_target] dictionary: 112832 types
| data-bin/writingPrompts test 15138 examples
| data-bin/writingPrompts test 15138 examples
| loading model(s) from models/writingPrompts/fusion_checkpoint.pt
| loading pretrained model
Traceback (most recent call last):
  File "generate.py", line 171, in <module>
    main(args)
  File "generate.py", line 44, in main
    models, _ = utils.load_ensemble_for_inference(args.path.split(':'), task, model_arg_overrides=eval(args.model_overrides))
  File "/home/ubuntu/work/fairseq/fairseq/utils.py", line 158, in load_ensemble_for_inference
    model = task.build_model(args)
  File "/home/ubuntu/work/fairseq/fairseq/tasks/fairseq_task.py", line 130, in build_model
    return models.build_model(args, self)
  File "/home/ubuntu/work/fairseq/fairseq/models/__init__.py", line 27, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/home/ubuntu/work/fairseq/fairseq/models/fconv_self_att.py", line 88, in build_model
    task=task,
  File "/home/ubuntu/work/fairseq/fairseq/utils.py", line 160, in load_ensemble_for_inference
    model.load_state_dict(state['model'], strict=True)
  File "/home/ubuntu/work/fairseq/fairseq/models/fairseq_model.py", line 64, in load_state_dict
    super().load_state_dict(state_dict, strict)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FConvModelSelfAtt:
	size mismatch for decoder.embed_tokens.weight: copying a param of torch.Size([112832, 256]) from checkpoint, where the shape is torch.Size([104960, 256]) in current model.
	size mismatch for decoder.fc3.weight: copying a param of torch.Size([112832, 256]) from checkpoint, where the shape is torch.Size([104960, 256]) in current model.
	size mismatch for decoder.fc3.bias: copying a param of torch.Size([112832]) from checkpoint, where the shape is torch.Size([104960]) in current model.
```

**Comment by myleott** [comment] 2018-09-07 15:51
@vanhuyz, I just downloaded the preprocessed test set from [here](https://github.com/pytorch/fairseq#stories) and confirmed that it works with the pretrained model. But if I preprocess the data myself then I get the same error as you.

@huihuifan, it seems the data preparation script doesn't quite match what was used for the pretrained models. In particular, there's some issue with tokenization on the target side:
```
> wc -l stories_test/dict.wp_target.txt writingPrompts/dict.wp_target.txt
 104956 stories_test/dict.wp_target.txt
 112828 writingPrompts/dict.wp_target.txt

> head stories_test/dict.wp_target.txt writingPrompts/dict.wp_target.txt
==> stories_test/dict.wp_target.txt <==
. 9101642
<newline> 7067574
, 7065933
the 5990261
I 3814404
to 3315010
and 2932963
a 2738379
of 2509242
was 1790379

==> writingPrompts/dict.wp_target.txt <==
. 10437996
> 8187647
< 8165665
newLine 8160893
, 8074997
the 6807661
I 4372362
to 3789707
and 3363691
a 3100025
```

Looking at the source files, it seems the raw writingPrompts training data is over-tokenized, at least for new lines:
```
> tail -n 1 ../writingPrompts/train.wp_target
Bob dropped five of the Zeds , reloaded his Colt 45 , and ran up the stairs . < newLine > < newLine > He had someone currently upstairs , (...)
```

**Comment by huihuifan** [comment] 2018-09-07 22:10
@myleott @elfsmelf @vanhuyz I pushed a change to the readme to clarify how the data should be preprocessed. 

The issue is that the data you download is the full dataset, but in the paper I only model the first 1k tokens of each story (as the full stories are quite long). I wrote this in the readme, but it's not in the copy pastable code part. I added to the readme some example python code to construct this, basically open the file in python and do some i[0:1000]. If I do this from scratch (mkdir test_data, cd test_data, then following the readme I do these steps: download data, preprocess the data, run preprocess.py), I can reproduce the correct vocabulary size. 

| [wp_source] Dictionary: 19024 types
| [wp_target] Dictionary: 104959 types

@myleott, I don't see the tokenization issue you mention.

**Comment by myleott** [comment] 2018-09-08 00:45
@huihuifan, you're right, I was using an old version of the archive I downloaded a while ago. The current version doesn't have any tokenization issue, just the length issue you mentioned.

**Comment by huihuifan** [comment] 2018-09-08 00:46
Ok, thanks for checking! :)  There was an older version of the dataset I had in AWS before I updated it.

**Comment by myleott** [comment] 2018-09-08 01:35
Closing. @vanhuyz, please feel free to reopen if you run into any issues

**Closed by myleott** 2018-09-08 01:35 UTC
