### ISSUE TITLE
multiple tasks dataloaders 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [pytorch/fairseq#2866] opened 2020-11-07 17:37 UTC
Hi,

I want to train a seq2seq model, but over multiple tasks, and the datasets are large, is there any implementation of such dataloader handling multiple tasks your could point me to. I appreciate your input on this.

thanks.

Best
Rabeeh

**Comment by alexeib** [comment] 2020-11-07 19:39
Duplicate of #2865

**Closed by alexeib** 2020-11-07 19:40 UTC
Labels: needs triage, question
