### ISSUE TITLE
Loading data from two data loaders with two training data iterators 

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#1747] opened 2020-02-25 22:51 UTC
### Motivation

Multitaks learning and Semi-Supervised Learning is getting so popular. So it is nice to have a feature that can load data from two uneven datasets in the sample time.

### Pitch

In the training loop, right now we get data from a group iterator. I want to get data from two group iterators in multi GPU training. Right now Multi-GPU setting is failing.

**Comment by myleott** [comment] 2020-02-26 15:47
Duplicate of #1746 :)

**Closed by myleott** 2020-02-26 15:47 UTC
Labels: enhancement, help wanted, needs triage
