### ISSUE TITLE
Zlib error: cannot load the model from torch hub

### ISSUE THREAD

**Issue by yrf1** [pytorch/fairseq#2674] opened 2020-09-29 15:56 UTC
> Traceback (most recent call last):
>     en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de.single_model', tokenizer='moses', bpe='fastbpe')
>   File "/home/yifung2/.local/lib/python3.6/site-packages/torch/hub.py", line 353, in load
>     model = entry(*args, **kwargs)
>   File "/home/yifung2/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/fairseq_model.py", line 255, in from_pretrained
>     **kwargs,
>   File "/home/yifung2/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 52, in from_pretrained
>     model_path = file_utils.load_archive_file(model_name_or_path)
>   File "/home/yifung2/.cache/torch/hub/pytorch_fairseq_master/fairseq/file_utils.py", line 81, in load_archive_file
>     top_dir = os.path.commonprefix(archive.getnames())
>   File "/usr/lib/python3.6/tarfile.py", line 1771, in getnames
>     return [tarinfo.name for tarinfo in self.getmembers()]
>   File "/usr/lib/python3.6/tarfile.py", line 1763, in getmembers
>     self._load()        # all members, we first have to
>   File "/usr/lib/python3.6/tarfile.py", line 2360, in _load
>     tarinfo = self.next()
>   File "/usr/lib/python3.6/tarfile.py", line 2291, in next
>     self.fileobj.seek(self.offset - 1)
>   File "/usr/lib/python3.6/gzip.py", line 368, in seek
>     return self._buffer.seek(offset, whence)
>   File "/usr/lib/python3.6/_compression.py", line 143, in seek
>     data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
>   File "/usr/lib/python3.6/gzip.py", line 471, in read
>     uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid literal/length code

Can someone help me with this please?

**Comment by myleott** [comment] 2020-09-29 21:54
I'm not able to reproduce this. Can you try again with `torch.hub.load(..., force_reload=True)`?

**Comment by yrf1** [comment] 2020-09-30 13:19
Same error with `force_reload=True`. 
I am running on python 3.6.9, torch 1.6.0 inside a lab server.

**Comment by myleott** [comment] 2020-09-30 15:28
Ah, glad clearing the cache solved it. Maybe there was some issue with the original download being corrupted? Closing for now, please reopen if this happens again

**Closed by myleott** 2020-09-30 15:28 UTC
Labels: Unable To Reproduce
