### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by bashartalafha** [pytorch/fairseq#427] opened 2018-12-31 13:47 UTC
Why running `generate.py` with different batch sizes results in different BLEU scores?

**Comment by myleott** [comment] 2018-12-31 13:50
This shouldn't happen... can you share the command you ran?

**Comment by myleott** [comment] 2018-12-31 14:31
Are you doing story generation or translation? The dataset suggests translation (`de-en`) but the fconv_self_att_wp architecture was originally designed for story generation.

**Comment by bashartalafha** [comment] 2018-12-31 14:32
Actually for translation

**Comment by bashartalafha** [comment] 2018-12-31 14:36
I'm trying in different languages, Bleu with 8 batch size 37.28 and with 32 batch size 36.5

**Comment by myleott** [comment] 2018-12-31 14:39
My guess is that that this has to do with padding. When using different batch sizes it also changes the amount of padding, which can change the results if the model is not careful about ignoring padding. The fconv_self_att_wp architecture was designed for story generation, not translation, so it probably doesn't mask out padding properly.

Is there some reason you'd like to use the fconv_self_att_wp architecture for translation? Otherwise, I'd recommending using the fconv architecture (pure convolution) or transformer (pure self-attention) architectures for translation.

**Comment by myleott** [comment] 2018-12-31 14:45
Yep, the fconv architecture masks padding after each convolution:
https://github.com/fairinternal/fairseq-py/blob/dc2094375e77b58b7e18d03b70ca8591bb132a8a/fairseq/models/fconv.py#L279-L280

But it looks like the fconv_self_att_wp architecture does not have this logic (since it probably wasn't important for the stories generation dataset):
https://github.com/fairinternal/fairseq-py/blob/dc2094375e77b58b7e18d03b70ca8591bb132a8a/fairseq/models/fconv_self_att.py#L202-L213

**Comment by bashartalafha** [comment] 2019-01-02 09:13
Actually I tried both `fconv` and `transformer` architectures, and both had good results, therefore I thought it would be a good idea to try a hybrid model between them. It seems that `fconv_self_att_wp` architecture combines both of them. That's why I'm trying to use the `fconv_self_att_wp` archi.

**Comment by huihuifan** [comment] 2019-01-07 10:09
Yes, indeed the fconv_self_att_wp model does not have the padding mask- seems that was my fault when adding the model, its functionality was not fully in sync with fconv. I will make a fix, but @bashartalafha, you could add it yourself as well.

**Comment by myleott** [comment] 2019-01-15 20:39
This should be fixed by #442. Please take a look and feel free to reopen if it's still a problem.

**Closed by myleott** 2019-01-15 20:39 UTC
