### ISSUE TITLE
speech_recognition with ctc_loss failed

### ISSUE THREAD

**Issue by luweishuang** [pytorch/fairseq#2107] opened 2020-05-08 09:40 UTC
## ❓ Questions and Help

I wanted used "--criterion ctc_loss" instead of "--criterion cross_entropy_acc" and other parameters keep the same with examples/speech_recognition/README.md, I got a "TypeError: build_criterion() missing 1 required positional argument: 'task'" and I don't know how to fix this error

**Comment by liangzhenlin123** [comment] 2020-05-24 15:46
+1, i get a same error after replacing "cross_entropy_acc" with "ctc_loss", and i doubt it is caused by the override function "build_criterion", since i have never seen it in "cross_entropy_acc"'s module. How can i use ctc loss?

**Comment by liangzhenlin123** [comment] 2020-05-24 16:07
i rty to comment “build_criterion” in the CTC_loss.py, then i can build the model and criterion, However, fairseq raise another error;
'CTCCriterion' object has no attribute 'args'
which is similar as issue
[https://github.com/pytorch/fairseq/issues/1802](url)
So this is a bug?

**Comment by myleott** [comment] 2020-05-28 14:55
This should be fixed now

**Closed by myleott** 2020-05-28 14:55 UTC
Labels: bug

**Comment by liangzhenlin123** [comment] 2020-05-28 16:10
Thanks a lot, BTW, there maybe anpther bug, when i use the infer.py in /examples/speech_recognition, when batchsize greater than 1, e.g., bsz=2, a Exception will be raised as follow:

memoryError: cuda runtime error(77):an illegal memory access was encountered at...

however, it will be fine if i use batchsize=1, while it is really slow when predict
