### ISSUE TITLE
Issue of running examples/speech_to_text/prep_mtedx_data.py

### ISSUE THREAD

**Issue by hygong-fb** [pytorch/fairseq#3303] opened 2021-03-03 23:15 UTC
#### What is your question?
I processed mTEDx data with examples/peech_to_text/prep_mtedx_data.py/, and got an error "Segmentation fault (core dumped)". As I traced back, the error is from ta_sox.apply_effects_tensor in data/audio/audio_utils.py

#### Code

Following the instructions in README to run the command:

```python
python examples/speech_to_text/prep_mtedx_data.py \
  --data-root ${MTEDX_ROOT} --task st \
  --vocab-type unigram --vocab-size 1000
```

#### What's your environment?
 - fairseq Version: 1.0.0a0+7d2394b 
 - torchaudio Version: 0.7.2
 - PyTorch Version: 1.7.1
 - How you installed fairseq: pip
 - Python version: 3.8
 - CUDA/cuDNN version: 11.0

**Comment by olafthiele** [comment] 2021-03-04 09:06
Same here

**Comment by gegallego** [comment] 2021-03-04 16:22
I have the same issue. As you mention, it is caused by `torchaudio` when transforming an audio to mono, using a `sox` effect.
https://github.com/pytorch/fairseq/blob/f6d60e2fee9fe8982e3c9de1e6bb77680978e749/fairseq/data/audio/audio_utils.py#L67

Does anyone know if `sox` averages channels to get the mono output? If it does, I would just substitute that line by:
```
waveform = torch.mean(waveform, dim=0, keepdim=True)
```

**Comment by kahne** [comment] 2021-03-04 21:17
Thanks all for reporting the issue! We are rolling out a bug fix on this. I will let you know when it's available in the main branch.

**Comment by kahne** [comment] 2021-03-05 02:28
The fix has been landed.

**Closed by kahne** 2021-03-05 02:28 UTC
Labels: needs triage, question, speech-to-text
