### ISSUE TITLE
Bart CNN example breaks

### ISSUE THREAD

**Issue by snailrowen1337** [pytorch/fairseq#3254] opened 2021-02-18 15:19 UTC
## 🐛 Bug

I am reproducing the Bart/CNN results from https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md, but the code crashes during inference.

### To Reproduce

Follow the instructions from https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md, exchange the architecture bart_large->bart_base during finetuning, the code then crashes at inference. I put the code mention in the instructions in ```eval_cnn.py```, i.e.

```
import torch
from fairseq.models.bart import BARTModel

bart = BARTModel.from_pretrained(
    'checkpoints/',
    checkpoint_file='checkpoint_best.pt',
    data_name_or_path='cnn_dm-bin'
)

bart.cuda()
bart.eval()
bart.half()
...
```

running this then yields

```
Traceback (most recent call last):
  File "eval_cnn.py", line 27, in <module>
    hypotheses_batch = bart.sample(slines, beam=4, lenpen=2.0, max_len_b=140, min_len=55, no_repeat_ngram_size=3)
  File "/home/fairseq/fairseq/hub_utils.py", line 132, in sample
    batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
  File "/home/fairseq/fairseq/models/bart/hub_interface.py", line 109, in generate
    **kwargs
  File "/home/fairseq/fairseq/hub_utils.py", line 174, in generate
    generator, self.models, batch, **inference_step_args
  File "/home/fairseq/fairseq/tasks/fairseq_task.py", line 501, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "/home/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/fairseq/fairseq/sequence_generator.py", line 182, in generate
    return self._generate(sample, **kwargs)
  File "/home/fairseq/fairseq/sequence_generator.py", line 353, in _generate
    step, lprobs, scores, tokens, prefix_tokens, beam_size
  File "/home/fairseq/fairseq/sequence_generator.py", line 560, in _prefix_tokens
    prefix_lprobs = lprobs.gather(-1, prefix_toks.unsqueeze(-1))
RuntimeError: Size does not match at dimension 0 expected index [128, 1] to be smaller than src [20, 50264] apart from dimension 1

```

### Expected behavior

It should not crash.

### Environment

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0) 1.7
 - OS (e.g., Linux): CentOs
 - How you installed fairseq (`pip`, source): pip
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: V100

**Comment by myleott** [comment] 2021-02-19 16:22
cc @sshleifer who was looking into this recently

**Comment by sshleifer** [comment] 2021-02-23 06:02
I can't replicate on master, can you verify that `56e76e0e1` is in your `git log`? The fix was on Feb 17.

**Comment by snailrowen1337** [comment] 2021-02-25 02:51
Just ran it from the latest committ, I have the following in my git log

```
commit b8651bc984413e7e45f44294dffcc85692ba89c1
Author: Weiyi Zheng <wyz@fb.com>
Date:   Wed Feb 24 15:48:38 2021 -0800
```

The issue I get now is:

```
RuntimeError: Error(s) in loading state_dict for BARTModel:
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([51201, 768]) from checkpoint, the shape in current model is torch.Size([50264, 768]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([51201, 768]) from checkpoint, the shape in current model is torch.Size([50264, 768]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([51201, 768]) from checkpoint, the shape in current model is torch.Size([50264, 768]).
```

the issue becomes resolved by reverting bart_base->bart_large. Are the different pretrained models available at https://github.com/pytorch/fairseq/tree/master/examples/bart trained with different vocabulary sizes? It should be possible to fine-tune on the CNN-DM task from bert-base too right?

**Comment by sshleifer** [comment] 2021-02-25 15:58
different vocab sizes? Yes, I've seen this before. The easiest fix is usually to compare the two dictionaries and manually resize the embeddings. Huggingface has some code to do the embeddings part of it [here](https://github.com/huggingface/transformers/blob/4b919657313103f1ee903e32a9213b48e6433afe/src/transformers/modeling_utils.py#L680).

### Related Issue:
In huggingface, (`bart-large-cnn`)[https://huggingface.co/facebook/bart-large/blob/main/config.json] and 
(`bart-base`)[https://huggingface.co/facebook/bart-base/blob/main/config.json] have different vocab sizes, because `bart-base` has an embedding associated with the mask token. Your difference is larger than 1, it seems.

**Comment by sshleifer** [comment] 2021-02-25 16:00
The second thrust of this question appears to be a duplicate of https://github.com/pytorch/fairseq/issues/2242

**Closed** 2021-02-25 16:02 UTC
Labels: bug
