### ISSUE TITLE
Extract feature from trained wav2vec model

### ISSUE THREAD

**Issue by AlonsoDiCandia** [pytorch/fairseq#2005] opened 2020-04-13 18:05 UTC
Hi everyone, i tried to extract the feature from trained wav2vec model (.pt) from the official github, using the complete librispeech equal to the paper but the script in /example/wav2vec/ called wav2vec_featurize.py generate me a lot of file with the extension ".h5context" and i dont know how use these files, someone can help me or orient me.
Also the command:

`$ PYTHONPATH /path/to/fairseq python examples/wav2vec/wav2vec_featurize.py --input /path/to/task/waves --output /path/to/output \
--model /model/path/checkpoint_best.pt --split train valid test`

Dont work for me, because PYTHONPATH say the file or directory dont exist, so, i run the command without PYTHONPATH, and work but generate the h5context files and not .hdf5 files.

My PYTHONPATH is this: `/home/alonso/virtual-env/w2v/lib/python3.6/site-packages:/home/alonso/fairseq/fairseq`

**Comment by myleott** [comment] 2020-05-01 11:39
It should be PYTHONPATH=... (note the missing equal sign), I’ll update the docs. 

As for how to use wav2vec_featurize.py, I’m not able to reproduce this h5context issue.

**Comment by myleott** [comment] 2020-05-19 18:17
Fixed in 9a718e29855713a51877237b2dcc25e39c234c82

**Closed by myleott** 2020-05-19 18:17 UTC
Labels: documentation
