### ISSUE TITLE
wav2vec 2.0

### ISSUE THREAD

**Issue by awasthiabhijeet** [pytorch/fairseq#2316] opened 2020-07-11 05:23 UTC
Hi,
Just curious to know when is [wav2vec 2.0](https://arxiv.org/abs/2006.11477) going to get released?

Thanks

**Comment by myleott** [comment] 2020-07-14 16:45
@alexeib

**Comment by alexeib** [comment] 2020-07-15 20:37
Duplicate of #2268

**Closed by alexeib** 2020-07-15 20:37 UTC
Labels: question
